In [1]:
from matplotlib import pyplot as pp
import random
import numpy as np
%matplotlib inline

In [2]:
random.seed(1)

In [3]:
house_size = [random.randrange(70,200) for i in range(10000)]

In [4]:
distance_from_citycenter = [random.randrange(1,30) for i in range(10000)]

In [5]:
floor = [random.randrange(1,20) for i in range(10000)]

In [6]:
house_price = []
for i in range(10000):
    price = house_size[i] * random.randrange(5e4,10e4) + distance_from_citycenter[i] * -1e5 \
    + floor[i] * 1e4 + random.randrange(1,1e6)
    house_price.append(price)    

In [7]:
x = [[1,house_size[i],distance_from_citycenter[i],floor[i]] for i in range(10000)]

In [8]:
X_matrix = np.array(x)

In [9]:
y_matrix = np.array(house_price)

In [10]:
y_matrix = y_matrix.reshape(len(y_matrix),1)

In [11]:
theta = [0 for i in range(4)]

In [12]:
theta_matrix = np.array(theta)
theta_matrix = theta_matrix.reshape(len(theta_matrix),1)

In [13]:
def cost_function(x,theta,y):
    y_pred = x.dot(theta)
    diff = y_pred - y
    squared_error = np.power(diff,2)
    return np.sum(squared_error)/(2 * len(y))

In [14]:
cost_function(X_matrix,theta_matrix,y_matrix)

48651163244797.211

In [15]:
def gradient(x,theta,y):
    y_pred = x.dot(theta)
    diff = y_pred - y
    gradient = (1/len(y)) * x.T.dot(diff)
    return gradient

In [16]:
gradient(X_matrix, theta_matrix, y_matrix)

array([[ -9.19190538e+06],
       [ -1.34075960e+09],
       [ -1.30132268e+08],
       [ -9.27774585e+07]])

In [17]:
theta_matrix = theta_matrix.astype('float64')

In [18]:
max_iter = 400
learning_rate = 0.00001

In [19]:
#for i in range(max_iter):
    #theta_matrix -= gradient(X_matrix, theta_matrix,y_matrix)*learning_rate
    #if (i+1) % 20 == 0:
        #print(cost_function(X_matrix,theta_matrix,y_matrix))

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
regr = LinearRegression()

In [22]:
regr.fit(X_matrix,y_matrix)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
regr.predict(X_matrix)

array([[  7420965.05535429],
       [  6486934.90471347],
       [ 10479231.63611528],
       ..., 
       [  7705124.92443057],
       [ 10452680.24433072],
       [ 13496954.95497284]])

In [24]:
y_matrix

array([[  6404290.],
       [  6938852.],
       [ 13606034.],
       ..., 
       [  8898087.],
       [  9154662.],
       [ 11193225.]])